import uuid
from datetime import datetime
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from app.database import get_db
from app.config import EXPORT_DIR

router = APIRouter()

# 版权水印(生成物内嵌品牌)
WATERMARK = "Generated by CunSub (czlab.dev | cunzhangblog.com)"


@router.post("/{project_id}")
def export(project_id: str, format: str = "srt"):
    db = get_db()
    rows = db.execute("SELECT * FROM subtitles WHERE project_id = ? ORDER BY idx", (project_id,)).fetchall()
    project = db.execute("SELECT * FROM projects WHERE id = ?", (project_id,)).fetchone()
    db.close()

    if not rows:
        raise HTTPException(400, "没有字幕可导出")

    if format == "srt":
        content = _to_srt(rows)
    elif format == "vtt":
        content = _to_vtt(rows)
    elif format == "ass":
        content = _to_ass(rows)
    else:
        raise HTTPException(400, "不支持的格式")

    # 文件名带品牌水印
    safe_name = (project["name"] or "project").strip().replace(" ", "_")
    file_name = f"{safe_name}_{format}_by_cunsub.{format}"
    file_path = EXPORT_DIR / file_name
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)

    _write_file_metadata(file_path)

    export_id = str(uuid.uuid4())
    now = datetime.now().isoformat()
    db = get_db()
    db.execute(
        "INSERT INTO exports (id, project_id, format, file_path, created_at) VALUES (?, ?, ?, ?, ?)",
        (export_id, project_id, format, str(file_path), now)
    )
    db.commit()
    db.close()

    return FileResponse(file_path, filename=file_name, media_type="application/octet-stream")


def _to_srt(rows) -> str:
    blocks = []
    for r in rows:
        blocks.append(
            f"{r['idx']}\n{r['start_time']} --> {r['end_time']}\n{r['text']}"
        )
    # 末尾加水印行(剪映不识别非标准行,已验证)
    return "\n\n".join(blocks) + "\n" + WATERMARK + "\n"


def _to_vtt(rows) -> str:
    lines = ["WEBVTT", ""]
    for r in rows:
        start = r["start_time"].replace(",", ".")
        end = r["end_time"].replace(",", ".")
        lines.append(f"{start} --> {end}")
        lines.append(r["text"])
        lines.append("")
    # VTT 用 NOTE 注释写版权
    lines.append(f"NOTE {WATERMARK}")
    return "\n".join(lines)


def _to_ass(rows) -> str:
    header = (
        "[Script Info]\n"
        "Title: CunSub\n"
        "ScriptType: v4.00+\n\n"
        "[V4+ Styles]\n"
        "Format: Name, Fontname, Fontsize, PrimaryColour, BackColour, Bold, Italic, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV\n"
        "Style: Default,Microsoft YaHei,42,&H00FFFFFF,&H80000000,0,0,1,2,0,2,20,20,40\n\n"
        "[Events]\n"
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
    )
    lines = [header]
    for r in rows:
        start = _srt_to_ass_time(r["start_time"])
        end = _srt_to_ass_time(r["end_time"])
        lines.append(f"Dialogue: 0,{start},{end},Default,,0,0,0,,{r['text']}")
    # ASS 用 Comment 行写版权(不会显示)
    lines.append(f"Comment: 0,0:00:00.00,0:00:00.00,Default,,0,0,0,,{WATERMARK}")
    return "\n".join(lines)


def _write_file_metadata(file_path):
    """写 Windows 文件元数据(NTFS 备用数据流),嵌入版权信息。
    仅 NTFS 文件系统支持,失败时静默忽略。
    """
    try:
        # 在文件属性里附加一个版权流,查看方式: dir /r 或支持 ADS 的工具
        stream = f"{file_path}:copyright"
        with open(stream, "w", encoding="utf-8") as f:
            f.write(WATERMARK)
    except OSError:
        pass


def _srt_to_ass_time(srt_time: str) -> str:
    h, m, s = srt_time.split(":")
    s, ms = s.split(",")
    return f"{int(h)}:{m}:{s}.{ms[:2]}"
