import os
import socket
import winreg
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

DATA_DIR = BASE_DIR / "data"
AUDIO_DIR = DATA_DIR / "audio"
EXPORT_DIR = DATA_DIR / "exports"
DB_PATH = DATA_DIR / "cunsub.db"

for d in [DATA_DIR, AUDIO_DIR, EXPORT_DIR]:
    d.mkdir(parents=True, exist_ok=True)

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL = "gemini-2.5-pro"

# ---- 版权信息(方案B:后端下发) ----
# 品牌信息统一由后端下发,前端渲染,防止他人仅改前端代码就抹掉版权
BRANDING = {
    "app_name": "CunSub",
    "app_desc": "AI字幕工作流助手",
    "lab_name": "村长实验室",
    "lab_url": "https://czlab.dev",
    "blog_name": "村长博客",
    "blog_url": "https://www.cunzhangblog.com",
    "watermark": "Generated by CunSub (czlab.dev | cunzhangblog.com)",
}
# 签名密钥:用于校验品牌信息完整性,防止篡改(开源项目里此密钥公开,属"增加难度"而非绝对防护)
BRANDING_SECRET = os.getenv("CUNSUB_BRANDING_SECRET", "cunsub-czlab-2026-br4nd")


def _read_registry_proxy() -> str:
    """从 Windows 注册表读取系统代理地址(原始 host:port)"""
    try:
        with winreg.OpenKey(
            winreg.HKEY_CURRENT_USER,
            r"Software\Microsoft\Windows\CurrentVersion\Internet Settings"
        ) as key:
            enable, _ = winreg.QueryValueEx(key, "ProxyEnable")
            if not enable:
                return ""
            server, _ = winreg.QueryValueEx(key, "ProxyServer")
            if not server:
                return ""
            if "=" in server:
                for part in server.split(";"):
                    if part.startswith(("https=", "http=")):
                        return part.split("=", 1)[1]
            return server
    except Exception:
        return ""


def _port_open(host: str, port: int, timeout: float = 1.0) -> bool:
    """检测端口是否在监听"""
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


def _detect_proxy() -> str:
    """探测可用代理:
    1. 如果直连 Google 能通(TUN 模式/全局 VPN),不使用代理
    2. .env 手动配置优先
    3. 注册表系统代理"""
    import httpx

    # 0. 先测直连 —— TUN 模式的 VPN(如小地球仪)直连即可
    try:
        with httpx.Client(timeout=3) as c:
            c.get("https://generativelanguage.googleapis.com")
        return ""  # 直连可用,不需要代理
    except Exception:
        pass  # 直连不通,继续找代理

    # 1. .env 手动配置
    manual = os.getenv("GEMINI_PROXY", "").strip()
    if manual:
        return manual

    # 2. 注册表系统代理
    reg_proxy = _read_registry_proxy()
    if not reg_proxy:
        return ""

    addr = reg_proxy.replace("http://", "").replace("socks5://", "").strip()
    if ":" not in addr:
        return ""
    host, port_str = addr.rsplit(":", 1)
    try:
        port = int(port_str)
    except ValueError:
        return ""

    if _port_open(host, port):
        return f"http://{host}:{port}"

    return ""


# 代理检测
GEMINI_PROXY = _detect_proxy()
if GEMINI_PROXY:
    os.environ["HTTP_PROXY"] = GEMINI_PROXY
    os.environ["HTTPS_PROXY"] = GEMINI_PROXY


def check_gemini_reachable() -> tuple[bool, str]:
    """检测 Gemini API 是否可达,返回 (是否可达, 提示信息)"""
    import httpx
    try:
        kwargs = {"timeout": 4}
        if GEMINI_PROXY:
            kwargs["proxy"] = GEMINI_PROXY
        with httpx.Client(**kwargs) as c:
            c.get("https://generativelanguage.googleapis.com")
        return True, "Gemini API 可达"
    except httpx.ConnectTimeout:
        if GEMINI_PROXY:
            return False, f"代理 {GEMINI_PROXY} 连接超时,请检查代理软件是否运行"
        return False, "无法连接 Google API,请打开代理软件后重启 CunSub"
    except httpx.ConnectError:
        if GEMINI_PROXY:
            return False, f"代理 {GEMINI_PROXY} 拒绝连接,请检查代理端口是否正确"
        return False, "无法连接 Google API,请打开代理软件后重启 CunSub"
    except Exception as e:
        return False, f"连接 Google API 失败: {type(e).__name__}: {e}"
